#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <unistd.h>

/*
 * Global variable declaration
 * Name           : data
 * Type           : int
 * Purpose        :
 *     - Shared data between producer and consumer threads.
 *     - The producer generates random values and stores them in this variable.
 *     - The consumer reads the data when it becomes available.
 */
int data = 0;

/*
 * Global variable declaration
 * Name           : data_ready
 * Type           : int (used as a boolean flag)
 * Purpose        :
 *     - Indicates whether new data is available for the consumer.
 *     - 0 means no data available, 1 means data is ready to be consumed.
 */
int data_ready = 0;

/*
 * Global variable declaration
 * Name           : numberLoop
 * Type           : int
 * Purpose        :
 *     - Defines how many times the producer and consumer loops will execute.
 */
int numberLoop = 10;

/*
 * Synchronization objects
 * mutex : protects access to the shared variable 'data'.
 * cond  : condition variable used to signal from producer to consumer.
 */
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t cond = PTHREAD_COND_INITIALIZER;

/*
 * Action function : Producer thread routine responsible for generating data.
 * Input param     : arg - unused (NULL).
 * Output param    : None (returns NULL).
 * Description     :
 *     - Loops 'numberLoop' times to simulate data production.
 *     - Generates a random integer (0–99) each iteration.
 *     - Locks the mutex before writing to shared data to ensure thread safety.
 *     - Sets 'data_ready' flag to 1 and signals the consumer via condition variable.
 *     - Unlocks the mutex after updating the shared data.
 *     - Sleeps for 1 second to simulate production delay.
 */
void *producer(void* arg)
{
    for (int i = 0; i < numberLoop; ++i)
    {
        int value = rand() % 100;

        pthread_mutex_lock(&mutex); // Protect shared data

        printf("Run thread Producer\n");
        data = value;
        printf("[Producer] Created data: %d\n", data);

        data_ready = 1;              // Indicate new data is available
        pthread_cond_signal(&cond);  // Notify the consumer
        pthread_mutex_unlock(&mutex);

        sleep(1); // Simulate work delay
    }
    return NULL;
}

/*
 * Action function : Consumer thread routine responsible for processing data.
 * Input param     : arg - unused (NULL).
 * Output param    : None (returns NULL).
 * Description     :
 *     - Loops 'numberLoop' times to consume data generated by the producer.
 *     - Locks the mutex before checking or reading shared data.
 *     - Uses pthread_cond_wait() to wait for the producer’s signal when no data is ready.
 *     - When notified, reads and processes the shared variable 'data'.
 *     - Resets 'data_ready' flag to 0 after consuming the data.
 *     - Unlocks the mutex before the next iteration.
 */
void *consumer(void* arg)
{
    for (int i = 0; i < numberLoop; ++i)
    {
        pthread_mutex_lock(&mutex); // Protect shared data

        printf("Run thread Consumer\n");

        // Wait until the producer signals that data is ready
        while (!data_ready)
        {
            pthread_cond_wait(&cond, &mutex);
        }

        printf("[Consumer] Received data: %d\n", data);
        data_ready = 0; // Mark data as consumed

        pthread_mutex_unlock(&mutex);
    }
    return NULL;
}

/*
 * Action function : Main function to create and synchronize producer and consumer threads.
 * Input param     : None (standard C main entry point).
 * Output param    : Integer value (0 for success).
 * Description     :
 *     - Initializes two threads: one producer and one consumer.
 *     - The producer generates random data; the consumer waits and consumes it.
 *     - Both threads coordinate using a mutex and a condition variable.
 *     - After threads finish, main joins both threads to ensure completion.
 *     - Destroys the mutex and condition variable to free system resources.
 */
int main()
{
    pthread_t threadProducer;
    pthread_t threadConsumer;

    // Create the producer and consumer threads
    pthread_create(&threadProducer, NULL, producer, NULL);
    pthread_create(&threadConsumer, NULL, consumer, NULL);

    // Wait for both threads to finish execution
    pthread_join(threadProducer, NULL);
    pthread_join(threadConsumer, NULL);

    // Destroy synchronization objects
    pthread_mutex_destroy(&mutex);
    pthread_cond_destroy(&cond);

    printf("Finished.\n");

    return 0;
}